# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wenyue Wang
description: > # this means to ignore newlines until "baseurl:"
  Yes, it's me. But don't always contact me!
repository: https://github.com/wemake-services/jekyll-theme-hackcss
baseurl: ""  # the subpath of your site, e.g. /blog
url: http://sobolevn.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: My email
email: wangwenyue@cumt.edu.cn

navigation:
  - text: Home
    url: /
  - text: data
    url: /docs
  - text: talks
    url: /examples

projects:
  - name: nothing
    description: 
    #link: https://sobolevn.github.io/git-secret
    #image: https://github.com/sobolevn/git-secret/blob/7c9ae0b1853d4c15549027524121b9e40219fe47/images/git-secret-sm.png?raw=true
  - name: nothing
    description:
    #link: https://github.com/sobolevn/awesome-cryptography
    #image: https://pbs.twimg.com/profile_images/751426570607271937/vGxpniun_400x400.jpg
  - name: nothing
    description: 
    #link: https://github.com/sobolevn/ecto_autoslug_field
  - name: nothing
    description: 
    #link: https://github.com/sobolevn/django-split-settings

social:
  - service: github
    username: woaiwenyue
    link: https://github.com/woaiwenyue
  - service: twitter
    username: Wenyue Wang
    link: https://twitter.com/realwenyuewang
